In [1]:
import numpy as np

# What are Numpy and Numpy Arrays?


## Numpy Arrays:

**NumPy** provides:

- An extension package to Python for multi-dimensional arrays.

- An implementation that is closer to hardware (efficiency).

- Package designed for scientific computation (convenience).

- An implementation of array oriented computing.


In [2]:
a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


**Why it is useful**: Memory-efficient container that provides fast numerical operations.

In [3]:
L = range(1000)
%timeit [i**2 for i in L]

34.3 μs ± 373 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [4]:
a = np.arange(1000)
%timeit a**2

663 ns ± 13.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# NumPy Reference Documentation

On the web: [Link](https://numpy.org/doc/)


**Interactive help:**





In [5]:
np.array?


Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [6]:
help(np.array)

Help on built-in function array in module numpy:

array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None
)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if 

## Looking For Something

In [8]:
np.con*?

np.concat
np.concatenate
np.conj
np.conjugate
np.convolve

## Import conventions
The recommended convention to import NumPy is:

In [9]:
import numpy as np

# Creating Arrays

## Manual Construction of Arrays

1. 1D

In [11]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [13]:
a.ndim #Gives the Dimensions

1

In [14]:
a.shape # Shape of the array

(5,)

In [16]:
len(a) #Lenght of the Array

5

2. 2D and 3D Array

In [17]:
b = np.array([[0, 1, 2], [3, 4, 5]]) 
b

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
b.ndim

2

In [19]:
b.shape

(2, 3)

In [ ]:
len(b) # returns the size of the first dimension

2

In [21]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [22]:
c.ndim

3

In [23]:
c.shape

(2, 2, 1)

In [24]:
len(c)

2

## Excercise

Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?

Use the functions len(), numpy.shape() on these arrays. How do they relate to each other? And to the ndim attribute of the arrays?

In [27]:
a = np.array([[9,7,5,3],[2,4,6,8]])
a

array([[9, 7, 5, 3],
       [2, 4, 6, 8]])

In [28]:
a.shape

(2, 4)

In [29]:
a.ndim

2

In [30]:
len(a)

2