In [2]:
import numpy as np

# What are Numpy and Numpy Arrays?


## 1. Numpy Arrays:

**NumPy** provides:

- An extension package to Python for multi-dimensional arrays.

- An implementation that is closer to hardware (efficiency).

- Package designed for scientific computation (convenience).

- An implementation of array oriented computing.


In [3]:
a = np.array([0,1,2,3,4,5])
print(a)

[0 1 2 3 4 5]


**Why it is useful**: Memory-efficient container that provides fast numerical operations.

In [4]:
L = range(1000)
%timeit [i**2 for i in L]

33.9 μs ± 306 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
a = np.arange(1000)
%timeit a**2

652 ns ± 7.78 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## 2. NumPy Reference Documentation

On the web: [Link](https://numpy.org/doc/)


**Interactive help:**





In [6]:
np.array?


Signature:
np.array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None,
)
Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      ndmax=0, like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    require

In [7]:
help(np.array)

Help on built-in function array in module numpy:

array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None
)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if 

## 3. Looking For Something

In [8]:
np.con*?

np.concat
np.concatenate
np.conj
np.conjugate
np.convolve

## 4. Import conventions
The recommended convention to import NumPy is:

In [9]:
import numpy as np

## 5. Creating Arrays

### Manual Construction of Arrays

1. 1D

In [10]:
a = np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [11]:
a.ndim #Gives the Dimensions

1

In [12]:
a.shape # Shape of the array

(5,)

In [13]:
len(a) #Lenght of the Array

5

2. 2D and 3D Array

In [14]:
b = np.array([[0, 1, 2], [3, 4, 5]]) 
b

array([[0, 1, 2],
       [3, 4, 5]])

In [15]:
b.ndim

2

In [16]:
b.shape

(2, 3)

In [17]:
len(b) # returns the size of the first dimension

2

In [18]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [19]:
c.ndim

3

In [20]:
c.shape

(2, 2, 1)

In [21]:
len(c)

2

## Excercise

Create a simple two dimensional array. First, redo the examples from above. And then create your own: how about odd numbers counting backwards on the first row, and even numbers on the second?

Use the functions len(), numpy.shape() on these arrays. How do they relate to each other? And to the ndim attribute of the arrays?

In [22]:
a = np.array([[9,7,5,3],[2,4,6,8]])
a

array([[9, 7, 5, 3],
       [2, 4, 6, 8]])

In [23]:
a.shape

(2, 4)

In [24]:
a.ndim

2

In [25]:
len(a)

2

## 6. Functions for Creating Arrays

In [32]:
#Evenly Space:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
b = np.arange(1,9,2) # start, end(exclusive),step
b

array([1, 3, 5, 7])

In [34]:
c = np.linspace(0,1,6) # Start , end, num-points
c

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [36]:
d = np.linspace(0,1,5, endpoint=False)
d

array([0. , 0.2, 0.4, 0.6, 0.8])

Common Arrays

In [37]:
a = np.ones((3,3)) #reminder(3,3) is a tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [41]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
d = np.diag(np.array([1,2,3,4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

- `np.random`: Random numbers

In [43]:
rng = np.random.default_rng(27446968)
a = rng.random(4)
a

array([0.64613018, 0.48984931, 0.50851229, 0.22563948])

In [44]:
b = rng.standard_normal(4) #Gaussain
b

array([-0.38250769, -0.61536465,  0.98131732,  0.59353096])

- Experiment with arange, linspace, ones, zeros, eye and diag.

In [45]:
a = np.arange(2,3,4)
print(f"Arrange:{a}")


b = np.linspace(0,1,3)
print(f"Linspace:{b}")


z = np.zeros((3,2))
print(f"Zeros Array:{z}")


o = np.ones((3,3))
print(f"Ones array:{o}")

d = np.diag(np.array([1,2,3,4]))
print(f"Diag function:{d}")

Arrange:[2]
Linspace:[0.  0.5 1. ]
Zeros Array:[[0. 0.]
 [0. 0.]
 [0. 0.]]
Ones array:[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Diag function:[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


- Create different kinds of arrays with random numbers.

In [48]:
rng = np.random.default_rng(5)
a = rng.random(6)
a

array([0.80500292, 0.80794079, 0.51532556, 0.28580138, 0.0539307 ,
       0.38336888])

- Try setting the seed before creating an array with random values.

In [51]:
uniform_floats = np.random.rand(5) 
random_integers = np.random.randint(10, 21, size=5) 
print(f"Seed Array\n:{random_integers}")

Seed Array
:[17 10 10 17 11]


- Look at the function np.empty. What does it do? When might this be useful?

In [53]:
a = np.empty(3)
a

array([0.80500292, 0.80794079, 0.51532556])

In [54]:
arr_2d = np.empty((2, 3), dtype=np.int32)
arr_2d

array([[ 2111141660,  1072284309, -1532970605],
       [ 1072290470,   133103829,  1071676812]], dtype=int32)

- Construct an array containing :1,2,3,4,5

In [56]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

- construct an array containing: -5, -4, -3, -2, -1

In [59]:
b = np.arange(-5,0)
b

array([-5, -4, -3, -2, -1])

- Construct: 2 4 6 8

In [63]:
c = np.arange(2,10,2)
c

array([2, 4, 6, 8])

- Construct 15 equispaced numbers in range [0, 10]


In [65]:
d = np.linspace(0,10,15)
d

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])